#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
#define YCBCR_IMPLEMENTATION
#define METRICS_NHW_IMPLEMENTATION
#define METRICS_PSNR_IMPLEMENTATION
#define METRICS_SMALLFRY_IMPLEMENTATION
#include "stb/stb_image.h"
#include "stb/stb_image_write.h"
#include "ycbcr.h"
#include "metricspsnr.h"
#include "metricsnhw.h"
#include "smallfry.h"
